import mongoose from 'mongoose';
import { patientSchema } from './mongodb/schemas/patient.schema';
import { doctorSchema } from './mongodb/schemas/doctor.schema';
import { appointmentSchema } from './mongodb/schemas/appointment.schema';
import { pharmacyCategorySchema } from './mongodb/schemas/pharmacyCategory.schema';
import { medicineSchema } from './mongodb/schemas/medicine.schema';
import { prescriptionSchema } from './mongodb/schemas/prescription.schema';
import { orderSchema } from './mongodb/schemas/order.schema';
import { medicineOrderSchema } from './mongodb/schemas/medicine-order.schema';
import { labTestOrderSchema } from './mongodb/schemas/lab-test-order.schema';
import { labTestCategorySchema } from './mongodb/schemas/labTestCategory.schema';
import { labTestSchema } from './mongodb/schemas/labTest.schema';
import { specializationSchema } from './mongodb/schemas/specialization.schema';

const PatientModel = mongoose.model('Patient', patientSchema);
const DoctorModel = mongoose.model('Doctor', doctorSchema);
const AppointmentModel = mongoose.model('Appointment', appointmentSchema);
const PharmacyCategoryModel = mongoose.model('PharmacyCategory', pharmacyCategorySchema);
const MedicineModel = mongoose.model('Medicine', medicineSchema);
const PrescriptionModel = mongoose.model('Prescription', prescriptionSchema);
const OrderModel = mongoose.model('Order', orderSchema);
const MedicineOrderModel = mongoose.model('MedicineOrder', medicineOrderSchema);
const LabTestOrderModel = mongoose.model('LabTestOrder', labTestOrderSchema);
const LabTestCategoryModel = mongoose.model('LabTestCategory', labTestCategorySchema);
const LabTestModel = mongoose.model('LabTest', labTestSchema);
const SpecializationModel = mongoose.model('Specialization', specializationSchema);


export { PatientModel };
export { DoctorModel };
export { AppointmentModel };
export { PharmacyCategoryModel };
export { MedicineModel };
export { PrescriptionModel };
export { OrderModel };
export { MedicineOrderModel };
export { LabTestOrderModel };
export { LabTestCategoryModel };
export { LabTestModel };
export { SpecializationModel };